matrix:
 include:
   - language: csharp
     mono: none
     dotnet: 3.1      
     install:
     - dotnet restore
     script:
     - dotnet build
     - dotnet test GymMovesWebAPI.Tests/GymMovesWebAPI.Tests.csproj
   - language: dart
     addons:
       apt:
         packages:
         - lib32stdc++6
     install:
     - git clone https://github.com/flutter/flutter.git -b beta
     - ./flutter/bin/flutter doctor
     script:
     - test test
     cache:
       directories:
       - $HOME/.pub-cache
