name: gym_moves
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adobe_xd:
  flutter:

    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  responsive_framework: ^0.0.7
  auto_size_text: ^2.1.0
  autocomplete_textfield: ^1.6.4
  rxdart: ^0.20.0
  http: ^0.12.1
  flutter_datetime_picker: ^1.3.8
  fluttertoast: ^4.0.0
  qr_flutter: ^3.1.0
  flutter_spinkit: ^4.1.2
  nfc_in_flutter: 2.0.2
  flutter_swiper: 1.1.6
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.12.9+5
  schedule_controller: ^0.1.3+1
  smooth_star_rating: 1.1.1
  crypto: ^2.1.4
  flutter_icons: ^1.1.0
  localstorage: ^3.0.2+5
  nearby_connections: ^1.0.3
  path_provider:


dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.6


flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/Roboto.ttf
    - family: Lastwaerk
      fonts:
       - asset: assets/Lastwaerk.ttf
    - family: Digital
      fonts:
        - asset: assets/DIGITALDREAMFATNARROW.ttf

  uses-material-design: true

  assets:
    - assets/MenuPicture.png
    - assets/Classes.png
    - assets/nfc.png
    - assets/SignupPicture.png
    - assets/profile.png
    - assets/notifications.png
    - assets/LoginPicture.png
    - assets/Mail.png
    - assets/ForgotPasswordPicture.png
    - assets/send.png
    - assets/ClassDetailsPicture.png