name: gym_moves
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adobe_xd:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  responsive_framework: ^0.0.7
  auto_size_text: ^2.1.0
  autocomplete_textfield: ^1.6.4
  rxdart: ^0.20.0
  http: ^0.12.1
  flutter_datetime_picker: ^1.3.8
  fluttertoast: ^4.0.0
  crypto: ^2.1.4
  flutter_swiper: ^1.1.6
  flutter_icons: ^1.0.0
  smooth_star_rating: ^1.1.1

dependency_overrides:
  flutter_datetime_picker:
    git:
      url: https://github.com/ditheshthegreat/flutter_datetime_picker # Repo
      ref: patch-1 # Branch name
  flutter_svg: ^0.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^0.5.6


flutter:
  fonts:
    - family: Lastwaerk
      fonts:
        - asset: assets/Lastwaerk.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto.ttf

  uses-material-design: true

  assets:
    - assets/SignupPicture.png
    - assets/LoginPicture.png
    - assets/ForgotPasswordPicture.png
    - assets/MenuPicture.png
    - assets/ClassDetailsPicture.png
    - assets/AddClassPicture.png
    - assets/Classes.png
    - assets/Mail.png
    - assets/nfc.png
    - assets/SetNotificationsPicture.png
    - assets/profile.png
    - assets/SendAnnouncementPicture.png

