name: gym_moves
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_datetime_picker: ^1.3.8
  fluttertoast: ^4.0.0
  http: ^0.12.1
  adobe_xd:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  flutter_svg: ^0.17.4

  responsive_framework: ^0.0.7

  auto_size_text: ^2.1.0

  autocomplete_textfield: ^1.6.4

  rxdart: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: FreestyleScript
      fonts:
        - asset: assets/FreestyleScript.ttf
    - family: Roboto
      fonts:
        - asset: assets/Roboto.ttf

  uses-material-design: true
  assets:
    - assets/Bicycles.jpg
    - assets/LeftSidePool.png
    - assets/leftSidePoolHalf.png
    - assets/RightSidePool.png
    - assets/RightSidePoolHalf.png
